# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('set_time', models.DateTimeField(auto_now=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=64)),
                ('user_email', models.CharField(max_length=100)),
                ('user_addr', models.CharField(max_length=200)),
                ('user_tel', models.CharField(max_length=11)),
                ('user_code', models.CharField(max_length=6)),
                ('user_recv', models.CharField(default='', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
